### ISSUE TITLE
Can't Get the Gem to Work in Rails

### ISSUE THREAD

**Issue by gcortes** [BrendanThompson/rb-scpt#1]
I loaded the code using the gem file. I wrote a stand alone test program and it works find. When I tried to do the same in a Rails controller, I get the error: 
# <NameError: uninitialized constant Appscript>

Has this gem ever been tested with Rails? I'm running Ruby 2.3.0 and Rails 5.0.0. I also have this question in [http://stackoverflow.com/questions/38418575/using-appscript-with-rails](url)

**Comment by BrendanThompson** [comment]
Hey Curt,

No, this hasn't been tested with rails unfortunately. Are you able to supply the error you're getting, or are you just getting the hash/pound?

Thanks,

Brendan

Sent from my iPhone

On 19 Jul. 2016, at 05:56, Curt Rowe <notifications@github.com<mailto:notifications@github.com>> wrote:

I loaded the code using the gem file. I wrote a stand alone test program and it works find. When I tried to do the same in a Rails controller, I get the error:

#

Has this gem ever been tested with Rails? I'm running Ruby 2.3.0 and Rails 5.0.0. I also have this question in http://stackoverflow.com/questions/38418575/using-appscript-with-rails<url>

##

**Comment by gcortes** [comment]
Sorry, the cut and paste didn't work. The error is:

`#<NameError: uninitialized constant Appscript>`

The line in error is:

`itu = ::Appscript.app('iTunes')`

This the complete program:

``` ruby
class ItunesController < ApplicationController
  def play
    itu = ::Appscript.app('iTunes')
    play_list = itu.sources[1].user_playlists.name.get
    render text(play_list)
  end
end
```

I tried adding a require, which I've never had to do with a gem. Just the straight require didn't find it. I then tried mapping it all the way to the gem in the vendor directory. It then complained about missing a require within rb-scpt. I've also tried 'by_name' and 'by_pid. I got the same error. My working stand alone program is in the root directory of the Rails project and works fine doing several different calls.

**Comment by gcortes** [comment]
I dug into the problem a little more. I put debug statements into the gem to see how far I could get. I got all the way to findapp.rb:

``` ruby
def FindApp._find_app(creator, id, name)
        begin
            return "got here: creator #{creator} id: #{id} name #{name}" ##################### debug
            return AE.find_application(creator, id, name)

```

The error is

```
<FindApp::ApplicationNotFoundError: Application \"got here: creator  id:  name iTunes.app\" not found.>
```

Any debug statement placed later isn't executed.

**Comment by gcortes** [comment]
I also tried this in my controller:

``` ruby
    itu = ::Appscript.app.by_pid(64394)
    @string_json = "{ 'result': '#{itu.class}' }"
    render json: @string_json
```

It renders: { 'result': 'Appscript::Application' }
If I change it to itu.to_s, I get: { 'result': 'app.by_pid(64394)' }

**Comment by gcortes** [comment]
One more note. I took out my debug steps and ran

``` ruby
 state = itu.player_state.get
```

I get back the response: Incomplete response received from application
At first I though this was directly from the browser. When I inspected it, I saw that it was a fully form html response. This must be from rb-scpt?

**Comment by BrendanThompson** [comment]
@gcortes are you still having an issue with `rb-scpt` with **Rails**?

**Comment by gcortes** [comment]
I never did get it to work. I ended taking a completely different approach that didn’t require rb-scpt.

**Comment by BrendanThompson** [comment]
@gcortes will close this issue off then. If you want to further investigate this happy to re-open.
