### ISSUE TITLE
String encoding support not enabled for Ruby version 2

### ISSUE THREAD

**Issue by Ontonator** [BrendanThompson/rb-scpt#10]
Unfortunately, I don't actually know enough about this project to know whether or not this is actually a bug, but this line (line 74) in `lib/_aem/encodingsupport.rb` seems suspect:
```ruby
return (version >= 1 and sub_version >= 9) ? AEMEncodingSupport::EnableStringEncodings : AEMEncodingSupport::DisableStringEncodings
```
It enables string encodings for Ruby version 1.9.x, but disables it again for version 2.x.x, and enables it again for version 2.9.x, 2.10.x, etc. for when they come out. Again, I'm not sure what the intended behaviour is, but I expect that this line should either read:
```ruby
return (version == 1 and sub_version >= 9) ? AEMEncodingSupport::EnableStringEncodings : AEMEncodingSupport::DisableStringEncodings
```
or
```ruby
return ((version == 1 and sub_version >= 9) or version >= 2) ? AEMEncodingSupport::EnableStringEncodings : AEMEncodingSupport::DisableStringEncodings
```

**Comment by zenspider** [comment]
They're all too complicated. This works just as well:

```ruby
    return RUBY_VERSION.to_f >= 1.9 ? AEMEncodingSupport::EnableStringEncodings : AEMEncodingSupport::DisableStringEncodings
```
