### ISSUE TITLE
minitest?

### ISSUE THREAD

**Issue by zenspider** [BrendanThompson/rb-scpt#2]
Would you like this ported to minitest? I saw something in rb-appscript that hinted that might be wanted.

One string tho: I'm not touching it until I have permission to indent the files properly. Tabs are NOT ruby-idiomatic.

**Comment by BrendanThompson** [comment]
@zenspider go for gold mate, and feel free to fix up the indenting too!

**Comment by zenspider** [comment]
Working on it...

**Comment by BrendanThompson** [comment]
@zenspider you still interested in working to port this to `minitest`

**Comment by zenspider** [comment]
This is done on my warnings PR #5

**Comment by BrendanThompson** [comment]
Closing the issue as it's catered for by #5 as @zenspider has stated.
