### ISSUE TITLE
Repo Admin Requests

### ISSUE THREAD

**Issue by zenspider** [BrendanThompson/rb-scpt#25]
To get things sorted out and less confusing, please do the following:

1. Mark master as the default branch
2. Delete or rebase develop against master to bring it up to date. I prefer deletion.

I can do 2 after 1 is done, making a new PR with anything that shakes out of the rebase

**Comment by zenspider** [comment]
I just rebased `develop` against current master and once the conflicts were resolved there were no differences at all. It should be deleted after master is made default. (ETA: pushed to show no differences)

**Comment by BrendanThompson** [comment]
Added PR with the latest CI changes into `master`, made it default, deleted `develop`
