### ISSUE TITLE
Please support/maintain this project

### ISSUE THREAD

**Issue by zenspider** [BrendanThompson/rb-scpt#9]
Please support this project. Either by responding and releasing as needed or by expanding the support you need to keep this project fresh. Otherwise, I'm going to be forced to fork and I don't want to have to do that. I have more than enough on my plate but I'm happy to contribute PRs to keep things moving.

**Comment by BrendanThompson** [comment]
Hey, have been a bit busy recently hence the lack of any updates. 

I am happy to have you as a maintainer on the project if you’re interested? I will try push some updates soon.

**Comment by zenspider** [comment]
Do it

ETA: this was ambiguous. Go ahead and add me as a maintainer. I'll try to work w/in your system but iirc, I had problems getting the project in working order last time I worked on a PR.

**Comment by BrendanThompson** [comment]
@zenspider have just added you now, sorry for delay. Might be an idea to catchup via some sort of IM?
